# Generated by Django 5.2.8 on 2025-11-12 18:53

import django.utils.timezone
from django.db import migrations, models
from django.contrib.auth.hashers import make_password

def seed_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    data = [
        dict(
            email='demo1@example.com',
            first_name='Demo',
            last_name='Uno',
            phone='600111222',
            address='Calle Falsa 123',
            city='Madrid',
            postal_code='28001',
            password=make_password('demo12345'),
            is_active=True,
        ),
        dict(
            email='demo2@example.com',
            first_name='Demo',
            last_name='Dos',
            phone='600333444',
            address='Av. Principal 456',
            city='Barcelona',
            postal_code='08001',
            password=make_password('demo12345'),
            is_active=True,
        ),
        dict(
            email='admin@petfun.local',
            first_name='Admin',
            last_name='PetFun',
            phone='600000000',
            address='Calle Admin 1',
            city='Madrid',
            postal_code='28000',
            password=make_password('Admin12345!'),
            is_active=True,
            is_staff=True,
            is_superuser=True,
        ),
    ]
    for row in data:
        if not User.objects.filter(email=row['email']).exists():
            User.objects.create(**row)


def unseed_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email__in=[
        'demo1@example.com',
        'demo2@example.com',
        'admin@petfun.local',
    ]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.RunPython(
            code=seed_users,
            reverse_code=unseed_users,
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
    ]

