# Generated by Django 5.2.6 on 2025-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_seed_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
    ]
