# Generated by Django 5.2.8 on 2025-11-12 18:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from decimal import Decimal
import random


# Functions from the following migrations manually copied below and referenced locally:
# - orders.migrations.0002_seed_sample_orders


def seed_orders(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    Product = apps.get_model('catalog', 'Product')

    products = list(Product.objects.all()[:20])
    if not products:
        return

    statuses = ['recibido', 'procesando', 'enviado', 'entregado', 'cancelado']

    for i in range(12):
        total = Decimal('0.00')
        order = Order.objects.create(
            user=None,
            contact_email=f"demo-tracking-{i}@example.com",
            total=Decimal('0.00'),
            status=random.choice(statuses),
            tracking_code=f"PT-DEMO-{i:03d}",
            ship_name=f"Cliente {i}",
            ship_street=f"Calle Demo {i}",
            ship_number=str(10 + i),
            ship_floor='',
            ship_city='Ciudad',
            ship_postal_code=f"28{100 + i}",
            ship_country='ES',
            payment_method='tarjeta',
        )
        for _ in range(random.randint(1, 3)):
            p = random.choice(products)
            qty = random.randint(1, 3)
            unit = p.price
            subtotal = unit * qty
            OrderItem.objects.create(
                order=order,
                product=p,
                product_name=p.name,
                quantity=qty,
                unit_price=unit,
                subtotal=subtotal,
            )
            total += subtotal
        order.total = total
        order.save(update_fields=['total'])


def unseed_orders(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(contact_email__startswith='demo-tracking-').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('recibido', 'Recibido'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], db_index=True, default='recibido', max_length=12)),
                ('ship_name', models.CharField(max_length=150)),
                ('ship_street', models.CharField(max_length=200)),
                ('ship_number', models.CharField(max_length=30)),
                ('ship_floor', models.CharField(blank=True, max_length=30)),
                ('ship_city', models.CharField(max_length=100)),
                ('ship_postal_code', models.CharField(max_length=20)),
                ('ship_country', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
        ),
        migrations.RunPython(
            code=seed_orders,
            reverse_code=unseed_orders,
        ),
    ]
# Generated by Django 5.2.8 on 2025-11-12 10:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recibido", "Recibido"),
                            ("procesando", "Procesando"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="recibido",
                        max_length=12,
                    ),
                ),
                ("ship_name", models.CharField(max_length=150)),
                ("ship_street", models.CharField(max_length=200)),
                ("ship_number", models.CharField(max_length=30)),
                ("ship_floor", models.CharField(blank=True, max_length=30)),
                ("ship_city", models.CharField(max_length=100)),
                ("ship_postal_code", models.CharField(max_length=20)),
                ("ship_country", models.CharField(max_length=100)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("tarjeta", "Tarjeta"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
